---
# NTP servers to sync with (public NTP pool by default)
ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

# Allow NTP clients from these networks
ntp_allow_networks:
  - 192.168.100.0/24

# Stratum level for this server
ntp_local_stratum: 3
