# code: language=ansible
---
all:
  hosts:
    glass:
      ansible_host: glass.home.d4n3sh.com
      ansible_user: danny
      ansible_connection: local
    naboo:
      ansible_user: danesh
    xwing:
      ansible_user: danesh
    ando:
      ansible_user: danesh
  children:
    docker:
      hosts:
        container01:
        naboo:
          ansible_user: danesh
        xwing:
          ansible_user: danesh
    podman:
      hosts:
        container02:
    ntp:
      hosts:
        bigben:
          ansible_host: 192.168.100.3
    dns:
      hosts:
        ns02:
          ansible_host: 192.168.100.4
    admin:
      hosts:
        admin01:
          ansible_host: admin01.home.d4n3sh.com
  vars:
    ansible_user: danny
    nfs_mounts:
      - src: nas.home.d4n3sh.com:/volume8/data/projects
        path: /home/danny/Projects
        state: mounted
      - src: truenas.home.d4n3sh.com:/mnt/default/data
        path: /mnt/truenas/data
        state: mounted
