# code: language=ansible
---
all:
  children:
    docker:
      hosts:
        container01:
        naboo:
          ansible_user: danesh
        xwing:
          ansible_user: danesh
    podman:
      hosts:
        container02:
    ntp:
      hosts:
        bigben:
          ansible_host: 192.168.100.3
    dns:
      hosts:
        ns02:
          ansible_host: 192.168.100.4
  vars:
    ansible_user: danny
