---
galaxy_info:
  author: d4n3sh
  description: Install and configure Podman container runtime
  company:
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - '7'
        - '8'
        - '9'
  galaxy_tags:
    - podman
    - containers
    - docker
    - container-runtime

dependencies: []
